---
- name: Configure Nginx web server
  hosts: all
  become: true
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: true

    - name: Deploy custom index.html
      copy:
        dest: /usr/share/nginx/html/index.html
        content: "<h1>Welcome to Nginx Server provisioned by Ansible!</h1>"
